version: 2
jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: 1d92386039c561396d412a18d8d171f5b3441cada3c23e513e414836eab92701
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - run: chmod +x ./cc-test-reporter
      - run: ./cc-test-reporter before-build
      - run: yarn test -- --coverage
      - run: ./cc-test-reporter after-build -t clover --exit-code $?


